# site settings
title: LeAnn McDowall
subtitle: data enthusiast
email: lm638@cornell.edu
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lhmcd.github.io"
author: LeAnn McDowall
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url: https://www.instagram.com/relaxidontbite/
linkedin_url: https://www.linkedin.com/in/leannmcdowall
pinterest_url:
slack_url:
twitter_url: https://twitter.com/LeAnnMcDowall

# build settings
markdown: kramdown

sass:
  style: compressed
